version: "3.8"
services:
  db:
    image: mysql:9.5.0
    # üè∑Ô∏è Name our container
    container_name: fx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Noragami12!
      MYSQL_DATABASE: fxwarehouse
      MYSQL_USER: fxuser
      MYSQL_PASSWORD: fxpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql # üíæ Save data permanently
    healthcheck: #  ü©∫ Check if database is healthy
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fxwarehouse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: fxuser
      SPRING_DATASOURCE_PASSWORD: fxpass
    ports:
      - "8080:8080"

volumes:
  mysql-data:
